_schema-version: '3.1'
ID: Monitor_Facturas
version: 1.0.0
description: A simple CAP project.
parameters:
  deploy_mode: html5-repo
  enable-parallel-deployments: true
  subdomain: colgas-4sieruf1
build-parameters:
  before-all:
    - builder: custom
      commands:
        - rm -rf build/dist
        - mkdir -p build/dist
        - rm -rf build/ui-deployer
        - mkdir -p build/ui-deployer
    - builder: custom
      commands:
        - npm install --production
        - >-
          bash -c "cds -v | grep 'cds-dk' || npm i --production --no-save
          @sap/cds-dk"
        - bash -c "export PATH=$PATH:$(pwd)/node_modules/.bin"
        - cds build --production
  after-all:
    - builder: custom
      commands:
        - npm install
modules:
  - name: Monitor_Facturas-monitorfacturas.detalleorden
    type: html5
    path: app/monitor_facturas.detalleorden
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/monitorfacturasdetalleorden.zip *"
      _artifactName: monitorfacturasdetalleorden.zip
      supported-platforms: []
      build-result: dist-zip
  - name: Monitor_Facturas-monitorfacturas.detallesfactura
    type: html5
    path: app/monitor_facturas.detallesfactura
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/monitorfacturasdetallesfactura.zip *"
      _artifactName: monitorfacturasdetallesfactura.zip
      supported-platforms: []
      build-result: dist-zip
  - name: Monitor_Facturas-monitorfacturas.entradas
    type: html5
    path: app/monitor_facturas.entradas
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/monitorfacturasentradas.zip *"
      _artifactName: monitorfacturasentradas.zip
      supported-platforms: []
      build-result: dist-zip
  - name: Monitor_Facturas-monitorfacturas.facturaorden
    type: html5
    path: app/monitor_facturas.facturaorden
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/monitorfacturasfacturaorden.zip *"
      _artifactName: monitorfacturasfacturaorden.zip
      supported-platforms: []
      build-result: dist-zip
  - name: Monitor_Facturas-monitorfacturas.facturasxml
    type: html5
    path: app/monitor_facturas.facturasxml
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/monitorfacturasfacturasxml.zip *"
      _artifactName: monitorfacturasfacturasxml.zip
      supported-platforms: []
      build-result: dist-zip
  - name: Monitor_Facturas-monitorfacturas.monitorfacturas
    type: html5
    path: app/monitor_facturas.monitorfacturas
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/monitorfacturasmonitorfacturas.zip *"
      _artifactName: monitorfacturasmonitorfacturas.zip
      supported-platforms: []
      build-result: dist-zip
  - name: Monitor_Facturas-monitorfacturas.ordendecompra
    type: html5
    path: app/monitor_facturas.ordendecompra
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/monitorfacturasordendecompra.zip *"
      _artifactName: monitorfacturasordendecompra.zip
      supported-platforms: []
      build-result: dist-zip
  - name: Monitor_Facturas-monitorfacturas.proveedores
    type: html5
    path: app/monitor_facturas.proveedores
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - >-
          bash -c "cd dist && npx bestzip
          ../dist-zip/monitorfacturasproveedores.zip *"
      _artifactName: monitorfacturasproveedores.zip
      supported-platforms: []
      build-result: dist-zip
  - name: Monitor_Facturas-db-deployer
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: Monitor_Facturas-service-uaa
      - name: Monitor_Facturas-service-db
  - name: Monitor_Facturas-srv
    type: nodejs
    path: gen/srv
    parameters:
      memory: 256MB
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: Monitor_Facturas-service-uaa
      - name: Monitor_Facturas-service-db
      - name: Monitor_Facturas-service-destination
      - name: Monitor_Facturas-service-metadata
      - name: Monitor_Facturas-service-connectivity
      - name: Monitor_Facturas-service-logs
  - name: Monitor_Facturas-aux-destinations
    type: com.sap.application.content
    parameters:
      content:
        subaccount:
          existing_destinations_policy: update
          destinations:
            - Authentication: OAuth2UserTokenExchange
              Name: Monitor_Facturas-service-uaa
              ServiceInstanceName: Monitor_Facturas-uaa
              ServiceKeyName: Monitor_Facturas-uaa-key
              sap.cloud.service: lcap.Monitor_Facturas
            - Authentication: OAuth2UserTokenExchange
              Name: Monitor_Facturas-app-srv
              TokenServiceInstanceName: Monitor_Facturas-uaa
              TokenServiceKeyName: Monitor_Facturas-uaa-key
              URL: ~{srv-api/srv-url}
              sap.cloud.service: lcap.Monitor_Facturas
            - Name: Monitor_Facturas-service-html5-apps-repo-host
              ServiceInstanceName: Monitor_Facturas-html5-apps-repo-host
              ServiceKeyName: Monitor_Facturas-html5-apps-repo-host-key
              sap.cloud.service: lcap.Monitor_Facturas
            - Authentication: OAuth2UserTokenExchange
              Name: Monitor_Facturas-Monitor_FacturasService
              TokenServiceInstanceName: Monitor_Facturas-uaa
              TokenServiceKeyName: Monitor_Facturas-uaa-key
              URL: ~{srv-api/srv-url}/service/Monitor_FacturasService
              sap.cloud.service: lcap.Monitor_Facturas
              sap.applicationdevelopment.actions.enabled: false
              sap.build.usage: CAP
              sap.processautomation.enabled: false
              HTML5.DynamicDestination: false
              WebIDEEnabled: false
              MobileEnabled: false
              AppgyverEnabled: false
    build-parameters:
      no-source: true
    requires:
      - name: Monitor_Facturas-service-uaa
        parameters:
          service-key:
            name: Monitor_Facturas-uaa-key
      - name: srv-api
      - name: Monitor_Facturas-service-html5-apps-repo-host
        parameters:
          service-key:
            name: Monitor_Facturas-html5-apps-repo-host-key
      - name: Monitor_Facturas-service-destination
        parameters:
          content-target: true
  - name: Monitor_Facturas-launchpad
    type: html5
    path: build/launchpad
    build-parameters:
      builder: custom
      commands:
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - bash -c "cd dist && npx bestzip ../../../build/dist/launchpad.zip *"
        - rm -rf dist
      _artifactName: launchpad.zip
      supported-platforms: []
      build-result: ../../build/dist
  - name: Monitor_Facturas-aux-ui-deployer
    type: com.sap.application.content
    path: build/ui-deployer
    build-parameters:
      build-result: resources
      requires:
        - name: Monitor_Facturas-monitorfacturas.detalleorden
          artifacts:
            - monitorfacturasdetalleorden.zip
          target-path: resources
        - name: Monitor_Facturas-monitorfacturas.detallesfactura
          artifacts:
            - monitorfacturasdetallesfactura.zip
          target-path: resources
        - name: Monitor_Facturas-monitorfacturas.entradas
          artifacts:
            - monitorfacturasentradas.zip
          target-path: resources
        - name: Monitor_Facturas-monitorfacturas.facturaorden
          artifacts:
            - monitorfacturasfacturaorden.zip
          target-path: resources
        - name: Monitor_Facturas-monitorfacturas.facturasxml
          artifacts:
            - monitorfacturasfacturasxml.zip
          target-path: resources
        - name: Monitor_Facturas-monitorfacturas.monitorfacturas
          artifacts:
            - monitorfacturasmonitorfacturas.zip
          target-path: resources
        - name: Monitor_Facturas-monitorfacturas.ordendecompra
          artifacts:
            - monitorfacturasordendecompra.zip
          target-path: resources
        - name: Monitor_Facturas-monitorfacturas.proveedores
          artifacts:
            - monitorfacturasproveedores.zip
          target-path: resources
        - name: Monitor_Facturas-launchpad
          artifacts:
            - launchpad.zip
          target-path: resources
    requires:
      - name: Monitor_Facturas-service-html5-apps-repo-host
        parameters:
          content-target: true
resources:
  - type: org.cloudfoundry.managed-service
    name: Monitor_Facturas-service-uaa
    parameters:
      service: xsuaa
      service-plan: application
      service-name: Monitor_Facturas-uaa
      path: xs-security.json
      config:
        oauth2-configuration:
          redirect-uris:
            - https://${subdomain}.launchpad.${default-domain}/login/*
            - https://${subdomain}.${default-domain}/login/*
          credential-types:
            - binding-secret
            - x509
        xsappname: Monitor_Facturas-${space}
        role-collections: []
  - type: org.cloudfoundry.managed-service
    name: Monitor_Facturas-service-db
    parameters:
      service: hana
      service-plan: hdi-shared
      service-name: Monitor_Facturas-db
  - type: org.cloudfoundry.managed-service
    name: Monitor_Facturas-service-destination
    parameters:
      service: destination
      service-plan: lite
      service-name: Monitor_Facturas-destination
      config:
        HTML5Runtime_enabled: true
        version: 1.0.0
  - type: org.cloudfoundry.user-provided-service
    name: Monitor_Facturas-service-metadata
    parameters:
      service: metadata
      service-plan: standard
      service-name: Monitor_Facturas-metadata
      config:
        default-domain: ${default-domain}
  - type: org.cloudfoundry.managed-service
    name: Monitor_Facturas-service-connectivity
    parameters:
      service: connectivity
      service-plan: lite
      service-name: Monitor_Facturas-connectivity
  - type: org.cloudfoundry.managed-service
    name: Monitor_Facturas-service-logs
    parameters:
      service: application-logs
      service-plan: lite
      service-name: Monitor_Facturas-logs
  - type: org.cloudfoundry.managed-service
    name: Monitor_Facturas-service-html5-apps-repo-host
    parameters:
      service: html5-apps-repo
      service-plan: app-host
      service-name: Monitor_Facturas-html5-apps-repo-host
