POST http://localhost:4004/service/Monitor_FacturasService/OrdenCompra
Content-Type: application/json

{

    "FechaCreacion": "2025-03-14",
    "ClasePedido": "2025-03-14",
    "NumeroOrden": "346346",
    "Proveedor": { "CodigoSap": "567568" },
    "UsuarioCreador": "Usuarioooo",
    "DetalleOrdenCompra": [
        {
            "NumeroMaterial": "Nhhg",
            "NombreMaterial": "Nhfghd",
            "GrupoArticulos": "dfhdf",
            "TipoMaterial": "dfhdf",
            "Cantidad": "107",
            "ValorUnitario": "1090190",
            "DepartamentoEntrega": "DepartamentoEntrega9852",
            "MunicipioEntrega": "MunicipioEntrega4813",
            "Direccion": "Direccion7454"
        }
    ]
}


###
POST http://localhost:4004/service/Monitor_FacturasService/Proveedores
Content-Type: application/json

{    
"CodigoSap": "000000",    
"Tratamiento": "Tratamiento",  
"Nombre1": "No1", 
"Nombre2": "No2",     
"Nombre3": "No3",     
"Nombre4": "No4",    
"Region": "Region453",     
"DescRegion": "DescRe34",   
"Municipio": "Municipio997",    
"Direccion": "Direccion8892",
"NIT": "NIT2106",    
"TipoNit": "TipoNit2867",  
"DescTipoNit": "DescTipoNiit5043",  
"Personanatural": "Personanatural8478",    
"ConceptoBusqueda": "Concepto",    
"Telefono": "21456336",  
"ClaseImpuesto": "Iva",    
"DescClaseImpuesto": "DescClase",    
"ConceptoBusqueda2": "ConceptoBusq",     
"CondicionPago": "Condici ",    
"DescCondicionPago": "DescCondicionPago183",   
"FechaInicio": "12-79-78", 
"FechaFin": "24-76-43",
"CorreoElectronico": "example@example"
    }

###
POST http://localhost:4004/service/Monitor_FacturasService/bulkInsertProveedores
Content-Type: application/json

{
  "proveedores": [
    {
      "CodigoSap": "000003",    
"Tratamiento": "Tratamiento",  
"Nombre1": "No1", 
"Nombre2": "No2",     
"Nombre3": "No3",     
"Nombre4": "No4",    
"Region": "Region453",     
"DescRegion": "DescRe34",   
"Municipio": "Municipio997",    
"Direccion": "Direccion8892",
"NIT": "NIT2106",    
"TipoNit": "TipoNit2867",  
"DescTipoNit": "DescTipoNiit5043",  
"Personanatural": "Personanatural8478",    
"ConceptoBusqueda": "Concepto",    
"Telefono": "21456336",  
"ClaseImpuesto": "Iva",    
"DescClaseImpuesto": "DescClase",    
"ConceptoBusqueda2": "ConceptoBusq",     
"CondicionPago": "Condici ",    
"DescCondicionPago": "DescCondicionPago183",   
"FechaInicio": "12-79-78", 
"FechaFin": "24-76-43",
"CorreoElectronico": "example@example"
    },
    {
      "CodigoSap": "000004",    
"Tratamiento": "Tratamiento",  
"Nombre1": "No1", 
"Nombre2": "No2",     
"Nombre3": "No3",     
"Nombre4": "No4",    
"Region": "Region453",     
"DescRegion": "DescRe34",   
"Municipio": "Municipio997",    
"Direccion": "Direccion8892",
"NIT": "NIT2106",    
"TipoNit": "TipoNit2867",  
"DescTipoNit": "DescTipoNiit5043",  
"Personanatural": "Personanatural8478",    
"ConceptoBusqueda": "Concepto",    
"Telefono": "21456336",  
"ClaseImpuesto": "Iva",    
"DescClaseImpuesto": "DescClase",    
"ConceptoBusqueda2": "ConceptoBusq",     
"CondicionPago": "Condici ",    
"DescCondicionPago": "DescCondicionPago183",   
"FechaInicio": "12-79-78", 
"FechaFin": "24-76-43",
"CorreoElectronico": "example@example"
    },
    {
      "CodigoSap": "000005",    
"Tratamiento": "Tratamiento",  
"Nombre1": "No1", 
"Nombre2": "No2",     
"Nombre3": "No3",     
"Nombre4": "No4",    
"Region": "Region453",     
"DescRegion": "DescRe34",   
"Municipio": "Municipio997",    
"Direccion": "Direccion8892",
"NIT": "NIT2106",    
"TipoNit": "TipoNit2867",  
"DescTipoNit": "DescTipoNiit5043",  
"Personanatural": "Personanatural8478",    
"ConceptoBusqueda": "Concepto",    
"Telefono": "21456336",  
"ClaseImpuesto": "Iva",    
"DescClaseImpuesto": "DescClase",    
"ConceptoBusqueda2": "ConceptoBusq",     
"CondicionPago": "Condici ",    
"DescCondicionPago": "DescCondicionPago183",   
"FechaInicio": "12-79-78", 
"FechaFin": "24-76-43",
"CorreoElectronico": "example@example"
    }
  ]
}


