/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const clientes_Logic = require('./code/clientes-logic');

class Monitor_FacturasService extends LCAPApplicationService {
    async init() {

        this.on(['CREATE', 'UPDATE'], 'Clientes', async (request, next) => {
            return clientes_Logic(request, next);
        });

        return super.init();
    }
}


module.exports = {
    Monitor_FacturasService
};