/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const detalleordencompra_Logic = require('./code/detalleordencompra-logic');

class Monitor_FacturasService extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'DetalleOrdenCompra', async (request) => {
            await detalleordencompra_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    Monitor_FacturasService
};